[tool.poetry]
name = "lazysvn"
version = "0.1.0"
description = ""
authors = ["DiwashRai <diwash.rai1993@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
